export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL="CREATE_ORDER_FAIL";

export const MYORDERS_REQUEST="MYORDERS_REQUEST";
export const MYORDERS_SUCCESS="MYORDERS_SUCCESS";
export const MYORDERS_FAIL="MYORDERS_FAIL";

export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL";

export const ORDERS_ADMIN_REQUEST="ORDERS_ADMIN_REQUEST";
export const ORDERS_ADMIN_SUCCESS="ORDERS_ADMIN_SUCCESS";
export const ORDERS_ADMIN_FAIL="ORDERS_ADMIN_FAIL";

export const UPDATE_ORDER_ADMIN_REQUEST="UPDATE_ORDER_ADMIN_REQUEST";
export const UPDATE_ORDER_ADMIN_SUCCESS="UPDATE_ORDER_ADMIN_SUCCESS";
export const UPDATE_ORDER_ADMIN_FAIL="UPDATE_ORDER_ADMIN_FAIL";
export const UPDATE_ORDER_ADMIN_RESET="UPDATE_ORDER_ADMIN_RESET";

export const DELETE_ORDER_ADMIN_REQUEST="DELETE_ORDER_ADMIN_REQUEST";
export const DELETE_ORDER_ADMIN_SUCCESS="DELETE_ORDER_ADMIN_SUCCESS";
export const DELETE_ORDER_ADMIN_FAIL="DELETE_ORDER_ADMIN_FAIL";
export const DELETE_ORDER_ADMIN_RESET="DELETE_ORDER_ADMIN_RESET";

export const CLEAR_ERRORS="CLEAR_ERRORS";
