export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL="CREATE_ORDER_FAIL";

export const MYORDERS_REQUEST="MYORDERS_REQUEST";
export const MYORDERS_SUCCESS="MYORDERS_SUCCESS";
export const MYORDERS_FAIL="MYORDERS_FAIL";

export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";
